msg = input()
m = msg.replace('10','ten')
m2 = m.replace('0','zero')
m3 = m2.replace('1','one')
m4 = m3.replace('2','two')
m5 = m4.replace('3','three')
m6 = m5.replace('4','four')
m7 = m6.replace('5','five')
m8 = m7.replace('6','six')
m9 = m8.replace('7','seven')
m0 = m9.replace('8','eight')
m1 = m0.replace('9','nine')

print(m1)
